sitesdata:
  image: pro100coder/enviroment:datastore-sites

mariadbdata:
  image: pro100coder/enviroment:datastore-mariadb

postgresdata:
  image: pro100coder/enviroment:datastore-postgres

solrdata:
  image: pro100coder/enviroment:datastore-solr

mongodata:
  image: pro100coder/enviroment:datastore-mongo

rabbitmqdata:
  image: pro100coder/enviroment:datastore-rabbitmq    
