ssh:
  image: pro100coder/enviroment:ssh
  ports:
   - 0.0.0.0:10022:22
  volumes_from:
   - enviroment_sitesdata_1
  links:
   - mariadb:mariadb
   - postgres:postgres
   - memcached:memcached
   - solr:solr

solr:
  image: pro100coder/enviroment:solr
  volumes_from:
    - enviroment_solrdata_1

php55:
  image: pro100coder/enviroment:php-5.5
  volumes_from:
   - enviroment_sitesdata_1
  links:
   - mariadb:mariadb
   - postgres:postgres
   - memcached:memcached
   - solr:solr

php52:
  image: pro100coder/enviroment:php-5.2
  volumes_from:
   - enviroment_sitesdata_1
  links:
   - mariadb:mariadb
   - postgres:postgres
   - memcached:memcached
   - solr:solr

nginx:
  image: pro100coder/enviroment:nginx
  ports:
   - 80:80
  links:
   - php55:php55
   - php52:php52
  volumes_from:
   - enviroment_sitesdata_1

mariadb:
  image: pro100coder/enviroment:mariadb
  environment:
   - MYSQL_ROOT_PASSWORD=root
  ports:
   - 3306:3306
  volumes_from:
   - enviroment_mariadbdata_1

postgres:
  image: postgres:9.3
  environment:
   - POSTGRES_PASSWORD=postgres
  ports:
   - 5432:5432
  volumes_from:
   - enviroment_postgresdata_1

memcached:
  image: memcached:1.4

nfs:
  image: pro100coder/enviroment:nfs
  command: /srv/www
  privileged: true
  ports:
   - 111:111
   - 2049:2049
  volumes_from:
   - enviroment_sitesdata_1
