ssh:
  image: pro100coder/enviroment:ssh
  ports:
    - 0.0.0.0:10022:22
  # volumes:
    # - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - enviroment_sitesdata_1
  links:
    - mariadb:mariadb
    - postgres:postgres
    - memcached:memcached
    - solr:solr

solr:
  image: pro100coder/enviroment:solr
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - enviroment_solrdata_1

php56:
  image: pro100coder/enviroment:php-5.6
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - enviroment_sitesdata_1
  links:
    - mariadb:mariadb
    - postgres:postgres
    - memcached:memcached
    - solr:solr

php55:
  image: pro100coder/enviroment:php-5.5
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - enviroment_sitesdata_1
  links:
    - mariadb:mariadb
    - postgres:postgres
    - memcached:memcached
    - solr:solr

php52:
  image: pro100coder/enviroment:php-5.2
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - enviroment_sitesdata_1
  links:
    - mariadb:mariadb
    - postgres:postgres
    - memcached:memcached
    - solr:solr

nginx:
  image: pro100coder/enviroment:nginx
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  ports:
    - 80:80
  links:
    - php56:php56
    - php55:php55
    - php52:php52
  volumes_from:
    - enviroment_sitesdata_1

mariadb:
  image: pro100coder/enviroment:mariadb
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - 3306:3306
  volumes_from:
    - enviroment_mariadbdata_1

postgres:
  image: postgres:9.3
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432:5432
  volumes_from:
    - enviroment_postgresdata_1

memcached:
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  image: memcached:1.4

samba:
  # volumes:
  #   - /etc/localtime:/etc/localtime:ro
  image: pro100coder/enviroment:samba
  ports:
   - 137:137
   - 138:138
   - 139:139
   - 445:445
  volumes_from:
   - enviroment_sitesdata_1
